# tasks file for nagios-server
---
- name: install | dependencies
  apt:
    name: "{{ nagios_server_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  register: apt_result
  until: apt_result is succeeded
